### ISSUE TITLE
Skill planner issue

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#120]
Hi

Got an exception with a skill Planner (from the current queue) open en trying to right click the topmost item in the live skill queue and choose add to 'Current skill queue' from the context menu in Evemon's main window/queue tab.

Note; I tried to add the topmost queue item (at level 5 while training dor it), so adding  a kind of duplicate entry already present in the skill planner.

EVEMon Version: 4.0.9.4882
.NET Runtime Version: 4.0.30319.42000
System.ArgumentException: This window doesn't support empty operations.
Parameter name: operation
   at EVEMon.SkillPlanner.PlanToOperationWindow..ctor(IPlanOperation operation) in EVEMon\SkillPlanner\PlanToOperationWindow.cs:line 44
   at EVEMon.CharacterMonitoring.CharacterSkillsQueueList.menuPlanItem_Click(Object sender, EventArgs e) in EVEMon\CharacterMonitoring\CharacterSkillsQueueList.cs:line 821
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by peterhaneve** [comment]
It seems like there are lots of these edge cases floating around, but all of them date from well before the ESI rework. I would have thought that most of these had been found by now...
