### ISSUE TITLE
Crash right after startup

### ISSUE THREAD

**Issue by WhyNotHugo** [peterhaneve/evemon#146]
Evemon crashes immediately after clicking `Add Character` when running under wine.

```
EVEMon Version: 4.0.11.4937
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
Executable Path: Z:\home\hugo\downloads\eve\EVEMon\EVEMon.exe
System.EntryPointNotFoundException: Unable to find an entry point named 'HttpCloseServerSession' in DLL 'httpapi.dll'.
   at System.Net.UnsafeNclNativeMethods.HttpApi.HttpCloseServerSession(UInt64 serverSessionId)
   at System.Net.HttpServerSessionHandle.ReleaseHandle()
   at System.Runtime.InteropServices.CriticalHandle.Cleanup()
   at System.Runtime.InteropServices.CriticalHandle.Dispose(Boolean disposing)
   at System.Net.HttpListener.SetupV2Config()
   at System.Net.HttpListener.ValidateV2Property()
   at EVEMon.Common.Service.SSOWebServer..ctor()
   at EVEMon.ApiCredentialsManagement.EsiKeyUpdateOrAdditionWindow..ctor()
   at EVEMon.MainWindow.addAPIKeyMenu_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


Datafile report:
  eve-blueprints-en-US.xml.gzip (224KiB - 5936d3167bcdf032568c77935bc84b0e)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (1010KiB - 062c656d9913c91533ec4bca655b4825)
  eve-items-en-US.xml.gzip (2477KiB - 92e7ab9a0f823d71df7120e473dccbce)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (62KiB - 5673fb8b543c187a90d8ed1870e29345)
  eve-reprocessing-en-US.xml.gzip (111KiB - 9c19069159e492f8486a58efcbb18bc8)
  eve-skills-en-US.xml.gzip (24KiB - bed294b41359401aeb808af2a59f3df4)


Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > EveMonClient.Initialize - done
0d 0h 00m 00s > Settings.Import - begin
0d 0h 00m 00s > EveMonClient.OnSchedulerChanged
0d 0h 00m 00s > Settings.Import - done
0d 0h 00m 00s > EveMonClient.OnSettingsChanged
0d 0h 00m 00s > Main loop - start
0d 0h 00m 00s > MainWindow.OnLoad
0d 0h 00m 00s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 00s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 00s > Main window - loaded
0d 0h 00m 00s > Datafiles.Load - begin
0d 0h 00m 01s > TimeCheck.BeginCheckAsync
0d 0h 00m 11s > TimeCheck.CheckFailure - Unknown error (0x274c)
0d 0h 00m 11s > TimeCheck.ScheduleCheck - in 00:01:00
0d 0h 00m 11s > EveMonClient.OnNotificationSent - Error querying the EVE server status. Check EVE server uptime on http://eve-offline.net/
0d 0h 00m 11s > UpdateManager - A request to raw.githubusercontent.com failed with status: ReceiveFailure.
0d 0h 00m 11s > UpdateManager.ScheduleCheck - in 00:01:00
0d 0h 00m 12s > Datafiles.Load - done
0d 0h 00m 12s > Settings.ImportData - begin
0d 0h 00m 12s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 12s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 12s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 13s > Settings.ImportData - done
0d 0h 00m 13s > EveMonClient.OnSettingsChanged
```

I set up the environment running:
```sh
winetricks corefonts dotnet461 tahoma gdiplus
```

**Comment by peterhaneve** [comment]
Wine currently does not work with EVEMon 4 due to the use of the built-in Windows (IIS-based) `HttpListener` class which Wine apparently does not implement. While this method avoids a firewall popup and does not require admin rights to run, the compatibility needs some work.

Unfortunately, adding "official" Wine compatibility is likely to expose other issues that may be difficult or impossible to fix. See #97.

**Comment by WhyNotHugo** [comment]
Is there any possible workaround for this?
I don't have access to any Windows machines, and `gtkevemon` has been kinda dead for a long while now.

**Comment by peterhaneve** [comment]
To fix your issue, I would have to rewrite the SSOListener to use a custom webserver. This would take a while, but I can consider putting it on the list.

The main issue is that once that is fixed, EVEMon probably has dozens of other hidden Wine only issues which will rear their heads then, and some might not be fixable or may cost significant effort.

**Comment by WhyNotHugo** [comment]
That sounds quite beyond my understanding (and kind of a rabbit hole too).

Do you think there's any chance of getting this to run with `mono`? The exception there is something entirely different (though I'm not sure how to copy it).

**Comment by peterhaneve** [comment]
Mono supposedly supports HTTPListener. What is the exception that occurs if you try it there?

**Comment by WhyNotHugo** [comment]
I can't copy the stacktrace, and the "copy details" button on the error message does nothing, so here's a screenshot of the error:

![2019-03-11T09:39:11,419232215-03:00](https://user-images.githubusercontent.com/730811/54124617-aa936600-43e1-11e9-8ff7-0bc5f7ad9166.png)

![2019-03-11T09:39:15,682937859-03:00](https://user-images.githubusercontent.com/730811/54124622-acf5c000-43e1-11e9-9b1f-4a79dd03b9b6.png)

![2019-03-11T09:39:19,513377223-03:00](https://user-images.githubusercontent.com/730811/54124624-aebf8380-43e1-11e9-98a8-af05eaa7cce3.png)

![2019-03-11T09:39:23,370210719-03:00](https://user-images.githubusercontent.com/730811/54124625-b0894700-43e1-11e9-8888-154158998973.png)

**Comment by peterhaneve** [comment]
It looks like Mono does not support this class either. However, Mono's `HttpListener` implementation is open source which may be useful as a substitute.
