### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#148]
Got a error today in the decoding of notifications (maybe caused by clicking a pilot to fast ater startup and looking at a notification). 

I have not been able to reproduce it.

```
System.InvalidCastException: Unable to cast object of type 'YamlDotNet.RepresentationModel.YamlScalarNode' to type 'System.IConvertible'.
   at System.Convert.ToBoolean(Object value)
   at EVEMon.Common.Models.Extended.InternalEveNotificationTextParser.Parse(EveNotification notification, KeyValuePair`2 pair, IDictionary`2 parsedDict) in EVEMon.Common\Models\Extended\InternalEveNotificationTextParser.cs:line 198
   at EVEMon.Common.Models.EveNotificationText.Parse(String textLayout) in EVEMon.Common\Models\EveNotificationText.cs:line 99
   at EVEMon.Common.Models.EveNotificationText.get_ParsedText() in EVEMon.Common\Models\EveNotificationText.cs:line 70
   at EVEMon.Common.Models.EveNotification.get_Text() in EVEMon.Common\Models\EveNotification.cs:line 125
   at EVEMon.Controls.ReadingPane.FormatLinks(IDictionary`2 replacements) in EVEMon\Controls\ReadingPane.cs:line 132
   at EVEMon.Controls.ReadingPane.TidyUpHTML() in EVEMon\Controls\ReadingPane.cs:line 101
   at EVEMon.Controls.ReadingPane.UpdatePane() in EVEMon\Controls\ReadingPane.cs:line 79
   at EVEMon.Controls.ReadingPane.set_SelectedObject(IEveMessage value) in EVEMon\Controls\ReadingPane.cs:line 49
   at EVEMon.CharacterMonitoring.CharacterEveNotificationsList.OnSelectionChanged() in EVEMon\CharacterMonitoring\CharacterEveNotificationsList.cs:line 607
   at EVEMon.CharacterMonitoring.CharacterEveNotificationsList.timer_Tick(Object sender, EventArgs e) in EVEMon\CharacterMonitoring\CharacterEveNotificationsList.cs:line 633
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by peterhaneve** [comment]
This is only attempted on the corvette reception notification after being without a ship. Since I see no reason to ever report this if it is `false` (otherwise the notification would not be sent) it might be safe to strip the check.
