### ISSUE TITLE
Unable to Launch

### ISSUE THREAD

**Issue by sidthekid100** [peterhaneve/evemon#160]
Getting this error when attempting to launcher EVEMon. Reinstalling doesn't change the issue, nor does installing on different drives.

`EVEMon Version: 4.0.11.4937
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.17134.0
Executable Path: "D:\eveMon\EVEMon.exe"
System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'EVEMon.Common.Settings' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at EVEMon.Common.MarketPricer.ItemPricer.get_Providers()
   at EVEMon.Common.SettingsObjects.MarketPricerSettings..ctor()
   at EVEMon.Common.Settings..cctor()
   --- End of inner exception stack trace ---
   at EVEMon.Common.Settings.Initialize()
   at EVEMon.Program.<StartupAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at EVEMon.Program.Main()
---> (Inner Exception #0) System.TypeInitializationException: The type initializer for 'EVEMon.Common.Settings' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at EVEMon.Common.MarketPricer.ItemPricer.get_Providers()
   at EVEMon.Common.SettingsObjects.MarketPricerSettings..ctor()
   at EVEMon.Common.Settings..cctor()
   --- End of inner exception stack trace ---
   at EVEMon.Common.Settings.Initialize()
   at EVEMon.Program.<StartupAsync>d__4.MoveNext()<---

System.TypeInitializationException: The type initializer for 'EVEMon.Common.Settings' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at EVEMon.Common.MarketPricer.ItemPricer.get_Providers()
   at EVEMon.Common.SettingsObjects.MarketPricerSettings..ctor()
   at EVEMon.Common.Settings..cctor()
   --- End of inner exception stack trace ---
   at EVEMon.Common.Settings.Initialize()
   at EVEMon.Program.<StartupAsync>d__4.MoveNext()

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at EVEMon.Common.MarketPricer.ItemPricer.get_Providers()
   at EVEMon.Common.SettingsObjects.MarketPricerSettings..ctor()
   at EVEMon.Common.Settings..cctor()

Datafile report:
  eve-blueprints-en-US.xml.gzip (224KiB - 5936d3167bcdf032568c77935bc84b0e)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (1010KiB - 062c656d9913c91533ec4bca655b4825)
  eve-items-en-US.xml.gzip (2477KiB - 92e7ab9a0f823d71df7120e473dccbce)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (62KiB - 5673fb8b543c187a90d8ed1870e29345)
  eve-reprocessing-en-US.xml.gzip (111KiB - 9c19069159e492f8486a58efcbb18bc8)
  eve-skills-en-US.xml.gzip (24KiB - bed294b41359401aeb808af2a59f3df4)

Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Program.StartupAsync - done
`

**Comment by peterhaneve** [comment]
A crash this early typically indicates an incompatible dependency. Which version of the .NET Framework is installed? EVEMon requires 4.6.1 as a minimum due to some of the cloud storage functions.

**Comment by sidthekid100** [comment]
https://i.imgur.com/VNpjDCS.png
My .NET Framework is, according to the installer, 4.7.2 at least. Any other
ideas? Thanks for the reply, btw

**Comment by peterhaneve** [comment]
This issue was fixed before in #103. It is possible that another program on your system has put a .DLL file of an incompatible dependency in either the global assembly cache or in the DLL search path (paths such as C:\WINDOWS\System32). Does the problem reproduce on another system?
