### ISSUE TITLE
Crash when trying to manage plans with broken skill plan on a character.

### ISSUE THREAD

**Issue by spookyglowingbadger** [peterhaneve/evemon#175]
A bit of a stupid issue. I've got a skill plan that has been edited manually to include an impossible skill level of 420, and now I'm unable to use the Manage plans function, as it crashes EVEMon.

EVEMon Version: 4.0.12.4946
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.18362.0
Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe" C:\Program Files (x86)\EVEMon\EVEMon.exe
System.NotImplementedException: One of our devs messed up. Skill level was 420 ?!
   at EVEMon.Common.Data.StaticSkill.GetPointsRequiredForLevel(Int64 level)
   at EVEMon.Common.Models.BaseCharacter.GetSPToTrain(StaticSkill skill, Int64 level, TrainingOrigin origin)
   at EVEMon.Common.Helpers.CharacterScratchpad.SetSkillLevel(StaticSkill skill, Int64 level, LearningOptions options)
   at EVEMon.Common.Helpers.CharacterScratchpad.TrainEntries(IEnumerable`1 entries, Boolean applyRemappingPoints)
   at EVEMon.Common.Models.BasePlan.GetTotalTime(CharacterScratchpad scratchpad, Boolean applyRemappingPoints)
   at EVEMon.SkillPlanner.PlanManagementWindow.UpdateContent(Boolean restoreSelectionAndFocus)
   at EVEMon.SkillPlanner.PlanManagementWindow.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Rest of logs redacted.

**Comment by peterhaneve** [comment]
I am going to lean towards "Won't Fix" here, but perhaps clamping skill levels might not be the worst idea on load.
