### ISSUE TITLE
EVEMon crashes under wine (macOS)

### ISSUE THREAD

**Issue by niveuseverto** [peterhaneve/evemon#191]
EVEMon Version: 4.0.14.4953
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
Executable Path: Z:\Users\niveuseverto\Downloads\EVEMon\EVEMon.exe
System.Net.HttpListenerException (0x80004005): Access denied
   at System.Net.HttpListener.SetupV2Config()
   at System.Net.HttpListener.ValidateV2Property()
   at EVEMon.Common.Service.SSOWebServer..ctor()
   at EVEMon.ApiCredentialsManagement.EsiKeyUpdateOrAdditionWindow..ctor()
   at EVEMon.ApiCredentialsManagement.EsiKeysManagementWindow.addESIKeyMenu_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Datafile report:
  eve-blueprints-en-US.xml.gzip (226KiB - 622f5004b558bf010e437cbc1e79aa0e)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (1010KiB - f1a27c1726f1db86b94765b60d876f4e)
  eve-items-en-US.xml.gzip (2574KiB - 022dfc6a7ce1d3e6ae5f6776a99fda9e)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (62KiB - 94f82ae5ddb964864ec83a26193365d2)
  eve-reprocessing-en-US.xml.gzip (111KiB - ef432cc5a832fbaeafb3ba5e7f16f06e)
  eve-skills-en-US.xml.gzip (24KiB - ca5f632c4d296ad59458e6eeabfb4b68)

Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > EveMonClient.Initialize - done
0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 00s > Settings.TryDeserializeFromFile - done
0d 0h 00m 00s > Settings.Import - begin
0d 0h 00m 00s > EveMonClient.OnSchedulerChanged
0d 0h 00m 00s > Settings.Import - done
0d 0h 00m 00s > EveMonClient.OnSettingsChanged
0d 0h 00m 00s > Main loop - start
0d 0h 00m 01s > MainWindow.OnLoad
0d 0h 00m 01s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 01s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 01s > Main window - loaded
0d 0h 00m 01s > Datafiles.Load - begin
0d 0h 00m 02s > TimeCheck.BeginCheckAsync
0d 0h 00m 02s > TimeCheck.OnCheckCompleted - Synchronised
0d 0h 00m 02s > TimeCheck.ScheduleCheck - in 1.00:00:00
0d 0h 00m 02s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 07s > Datafiles.Load - done
0d 0h 00m 07s > Settings.ImportData - begin
0d 0h 00m 07s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 07s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 07s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 07s > Settings.ImportData - done
0d 0h 00m 07s > EveMonClient.OnSettingsChanged
0d 0h 00m 13s > UpdateManager.OnCheckCompleted
0d 0h 00m 13s > UpdateManager.ScheduleCheck - in 12:00:00

**Comment by peterhaneve** [comment]
EVEMon has problems with Wine as it does not ship some required DLLs. See issue #97.
