### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by NikolasCalypso** [peterhaneve/evemon#206]
Most of the time I get error 403 forbidden when trying to fetch skill queue, (or no error but no update) and so it stays cached and doesn't actually update the queue information.

I don't have the actual error up right now, but it didn't seem too helpful. It said "not allowed", which is just another term for "forbidden", the 403 error. If you need the stack trace, I can grab it next time it comes up.

I've tried clearing the cache, and updating my login, but its still having a lot of problems.

Windows 10
Evemon 4.0.15 (64 bit)

**Comment by NikolasCalypso** [comment]
Here's the full error:

`EVEMon.Common.Net.HttpWebClientServiceException: A request to esi.evetech.net was not permitted. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at EVEMon.Common.Net.HttpClientServiceRequest.EnsureSuccessStatusCode(HttpResponseMessage response)
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Net.HttpWebClientService.<DownloadStreamAsync>d__11`1.MoveNext()`

**Comment by peterhaneve** [comment]
403 errors usually mean that you need to update your ESI key. Try using Reset Settings to see if there are old and invalid ESI keys in the settings file.

Unfortunately the EVEMon backend does not currently give much information about which request failed.
