### ISSUE TITLE
Error looking up character identities

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#218]
As my issue with PI and Contracts continue I cleared EveMon's cache and am now getting 'Error looking up character identities' errors.

EVEMon.Common.Net.HttpWebClientServiceException: A request to esi.evetech.net failed with status: 404 (Not Found). ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at EVEMon.Common.Net.HttpClientServiceRequest.EnsureSuccessStatusCode(HttpResponseMessage response) in C:\Users\Wim van der Vegt\Source\Repos\evemon\src\EVEMon.Common\Net\HttpClientServiceRequest.cs:line 122
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext() in C:\Users\Wim van der Vegt\Source\Repos\evemon\src\EVEMon.Common\Net\HttpClientServiceRequest.cs:line 65
   --- End of inner exception stack trace ---
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext() in C:\Users\Wim van der Vegt\Source\Repos\evemon\src\EVEMon.Common\Net\HttpClientServiceRequest.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at EVEMon.Common.Net.HttpWebClientService.<DownloadStreamAsync>d__11`1.MoveNext() in C:\Users\Wim van der Vegt\Source\Repos\evemon\src\EVEMon.Common\Net\HttpWebClientService.StreamDownload.cs:line 36

**Comment by wvdvegt** [comment]
I've added some lines to HttpClientServiceMessage.EnsureSuccessStatusCode to be able to see the offending URL during debugging (and be able to set a breakpoint). Changed:

```
                // Allow "not modified" so that it will be detected by the front end
                response.EnsureSuccessStatusCode();
```
into:
```
                // Allow "not modified" so that it will be detected by the front end
                if (!response.IsSuccessStatusCode)
                {
                    Console.WriteLine($"{(int)response.StatusCode} {response.RequestMessage.RequestUri}");
                }
                response.EnsureSuccessStatusCode();
```

First URL to generate a 400 response is:

**https://imageserver.eveonline.com/character/<id>_128.jpg**


which should be:

**http://image.eveonline.com/Character/<ic>_128.jpg**
