### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#237]
Got the following Crash Report:
Pilot has skills in it's queue (new Vorton related skills), but is not training them.  

EVEMon Version: 4.0.17.4966
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.18363.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at EVEMon.Common.Models.QueuedSkill.get_CurrentSP() in EVEMon.Common\Models\QueuedSkill.cs:line 105
   at EVEMon.CharacterMonitoring.CharacterSkillsQueueList.DrawItem(QueuedSkill skill, DrawItemEventArgs e) in EVEMon\CharacterMonitoring\CharacterSkillsQueueList.cs:line 231
   at EVEMon.CharacterMonitoring.CharacterSkillsQueueList.lbSkillsQueue_DrawItem(Object sender, DrawItemEventArgs e) in EVEMon\CharacterMonitoring\CharacterSkillsQueueList.cs:line 199
   at System.Windows.Forms.ListBox.OnDrawItem(DrawItemEventArgs e)
   at EVEMon.Common.Controls.NoFlickerListBox.OnDrawItem(DrawItemEventArgs e) in EVEMon.Common\Controls\NoFlickerListBox.cs:line 40
   at System.Windows.Forms.ListBox.WmReflectDrawItem(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at EVEMon.Common.Controls.NoFlickerListBox.WndProc(Message& m) in EVEMon.Common\Controls\NoFlickerListBox.cs:line 87
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by wvdvegt** [comment]
Does not reproduce under a debugger (but the queue seemed a bit off shortly (duplicate entries etc)).

**Comment by wvdvegt** [comment]
But i now see that he topmost skill says 'Gallente Destroyer' but is actually a new Edencom/Vorton related skill (right click says 'Add Unknown Skill').

**Comment by wvdvegt** [comment]
Got it reproducing under a debugger

In **QueueSkill.cs**, the property **CurrentSP** is where the exception starts as **SkillPointsPerHour** in the code below has an **Infinite** value somehow.

```
public int CurrentSP
        {
            get
            {
                int estimatedSP = (int)(EndSP - EndTime.Subtract(DateTime.UtcNow).TotalHours *
                    SkillPointsPerHour);
                return IsTraining ? Math.Max(estimatedSP, StartSP) : StartSP;
            }
        }
```

In the **SkillPerHour** calculation the **EndTime.Subtract(StartTime).TotalHours** returns 0 as **EndTime** is equal to **StartTime**. Probably because the skill was trained using login campaign gifted SP.

**Comment by wvdvegt** [comment]
Changed SkillPointsPerHour  into:
```
        public double SkillPointsPerHour => (Skill == Skill.UnknownSkill && EndTime > StartTime) ?
            Math.Ceiling((EndSP - StartSP) / EndTime.Subtract(StartTime).TotalHours) :
            Skill.SkillPointsPerHour;
```
But that results an error in DrawProgressionBar caused by CharacterSkillsQueueList.DrawItem as fractionCompleted is also infinite.

Changing the fractionCompleted calculation in CharacterSkillsQueueList.DrawItem to 
```
            double fractionCompleted = e.Index == 0 && !double.IsInfinity(skill.FractionCompleted)
                ? skill.FractionCompleted
                : 0d;
```
This seems to fix the crashes (but the progressbar will be zero and the remaining time also incorrect).

**Comment by wvdvegt** [comment]
The remaining time can be fixed for example with the line below in  CharacterSkillsQueueList.DrawItem:

            string trainingTimeText = $" Training Time: {(double.IsInfinity(skill.FractionCompleted) ? "n/a" : remainingTimeText)}";

**Comment by ritingon** [comment]
Similar issue here:

```EVEMon Version: 4.0.17.4966
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.18362.0
Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe" 
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\JB\AppData\Local\Temp\tmpF0A6.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at EVEMon.Common.Helpers.FileHelper.<OverwriteOrWarnTheUserAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Service.LocalXmlCache.<SaveAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Service.EveIDToName.<SaveImmediateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Service.EveIDToName.<EveMonClient_TimerTick>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at EVEMon.Program.<StartupAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at EVEMon.Program.Main()
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\JB\AppData\Local\Temp\tmpF0A6.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at EVEMon.Common.Helpers.FileHelper.<OverwriteOrWarnTheUserAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Service.LocalXmlCache.<SaveAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Service.EveIDToName.<SaveImmediateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Service.EveIDToName.<EveMonClient_TimerTick>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at EVEMon.Program.<StartupAsync>d__4.MoveNext()<---


System.IO.IOException: The process cannot access the file 'C:\Users\JB\AppData\Local\Temp\tmpF0A6.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at EVEMon.Common.Helpers.FileHelper.<OverwriteOrWarnTheUserAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Service.LocalXmlCache.<SaveAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Service.EveIDToName.<SaveImmediateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Service.EveIDToName.<EveMonClient_TimerTick>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at EVEMon.Program.<StartupAsync>d__4.MoveNext()


Datafile report:
  eve-blueprints-en-US.xml.gzip (233KiB - 3429df4087134b8ba91327ce7e348943)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (1015KiB - bd6283bee820dd226df3af61d93215cc)
  eve-items-en-US.xml.gzip (3400KiB - b3ed7b991afbd36ccf2f2a4a77c6ef9e)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (54KiB - bfa88d7e71747815ba1d3ef8e9a27a89)
  eve-reprocessing-en-US.xml.gzip (114KiB - b974861590311560a8649d583d3fab82)
  eve-skills-en-US.xml.gzip (25KiB - 703e1ef01cd4634ed39d86466b4ce32e)


Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Program.StartupAsync - done
0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 00s > Settings.TryDeserializeFromFile - done
0d 0h 00m 00s > Settings.Import - begin
0d 0h 00m 00s > EveMonClient.OnSchedulerChanged
0d 0h 00m 00s > Settings.Import - done
0d 0h 00m 00s > EveMonClient.OnSettingsChanged
0d 0h 00m 00s > Main loop - start
0d 0h 00m 00s > MainWindow.OnLoad
0d 0h 00m 00s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 00s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 00s > Main window - loaded
0d 0h 00m 01s > Datafiles.Load - begin
0d 0h 00m 01s > TimeCheck.BeginCheckAsync
0d 0h 00m 02s > TimeCheck.OnCheckCompleted - Synchronised
0d 0h 00m 02s > TimeCheck.ScheduleCheck - in 1.00:00:00
0d 0h 00m 02s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 06s > Datafiles.Load - done
0d 0h 00m 06s > Settings.ImportData - begin
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Ra'ita
0d 0h 00m 06s > EveMonClient.OnCharacterImplantSetCollectionChanged - Ra'ita
0d 0h 00m 06s > EveMonClient.OnCharacterSkillQueueUpdated - Ra'ita
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Ra'ita
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Anika Dark
0d 0h 00m 06s > EveMonClient.OnCharacterImplantSetCollectionChanged - Anika Dark
0d 0h 00m 06s > EveMonClient.OnCharacterSkillQueueUpdated - Anika Dark
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Anika Dark
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Zhilia Mann
0d 0h 00m 06s > EveMonClient.OnCharacterImplantSetCollectionChanged - Zhilia Mann
0d 0h 00m 06s > EveMonClient.OnCharacterSkillQueueUpdated - Zhilia Mann
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Zhilia Mann
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Anthony VonBrewskies
0d 0h 00m 06s > EveMonClient.OnCharacterImplantSetCollectionChanged - Anthony VonBrewskies
0d 0h 00m 06s > EveMonClient.OnCharacterSkillQueueUpdated - Anthony VonBrewskies
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Anthony VonBrewskies
0d 0h 00m 07s > EveMonClient.OnCharacterUpdated - Doma I Magnetoque
0d 0h 00m 07s > EveMonClient.OnCharacterImplantSetCollectionChanged - Doma I Magnetoque
0d 0h 00m 07s > EveMonClient.OnCharacterSkillQueueUpdated - Doma I Magnetoque
0d 0h 00m 07s > EveMonClient.OnCharacterUpdated - Doma I Magnetoque
0d 0h 00m 07s > EveMonClient.OnCharacterUpdated - Dodixie Flatline
0d 0h 00m 07s > EveMonClient.OnCharacterImplantSetCollectionChanged - Dodixie Flatline
0d 0h 00m 07s > EveMonClient.OnCharacterSkillQueueUpdated - Dodixie Flatline
0d 0h 00m 07s > EveMonClient.OnCharacterUpdated - Dodixie Flatline
0d 0h 00m 07s > EveMonClient.OnCharacterUpdated - Uinen Star
0d 0h 00m 07s > EveMonClient.OnCharacterImplantSetCollectionChanged - Uinen Star
0d 0h 00m 07s > EveMonClient.OnCharacterSkillQueueUpdated - Uinen Star
0d 0h 00m 07s > EveMonClient.OnCharacterUpdated - Uinen Star
0d 0h 00m 07s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 07s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - Ra'ita
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - Anika Dark
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - Zhilia Mann
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - Anthony VonBrewskies
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - Doma I Magnetoque
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - Dodixie Flatline
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - Uinen Star
0d 0h 00m 07s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 07s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 08s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 08s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 09s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 09s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 10s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 10s > Settings.ImportData - done
0d 0h 00m 10s > EveMonClient.OnSettingsChanged
0d 0h 00m 11s > EveMonClient.OnCharacterUpdated - Anika Dark
0d 0h 00m 11s > EveMonClient.OnCharacterListUpdated - 132378711614147097 (Anika Dark)
0d 0h 00m 11s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 11s > EveMonClient.OnESIKeyInfoUpdated - 132378711614147097 (Anika Dark)
0d 0h 00m 11s > EveMonClient.OnCharacterUpdated - Ra'ita
0d 0h 00m 11s > EveMonClient.OnCharacterListUpdated - 132378711267913573 (Ra'ita)
0d 0h 00m 11s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 11s > EveMonClient.OnESIKeyInfoUpdated - 132378711267913573 (Ra'ita)
0d 0h 00m 11s > EveMonClient.OnCharacterUpdated - Zhilia Mann
0d 0h 00m 11s > EveMonClient.OnCharacterListUpdated - 132378711782049992 (Zhilia Mann)
0d 0h 00m 11s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 11s > EveMonClient.OnESIKeyInfoUpdated - 132378711782049992 (Zhilia Mann)
0d 0h 00m 11s > EveMonClient.OnCharacterUpdated - Doma I Magnetoque
0d 0h 00m 11s > EveMonClient.OnCharacterListUpdated - 132378712197151669 (Doma I Magnetoque)
0d 0h 00m 11s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 11s > EveMonClient.OnESIKeyInfoUpdated - 132378712197151669 (Doma I Magnetoque)
0d 0h 00m 11s > EveMonClient.OnCharacterUpdated - Uinen Star
0d 0h 00m 11s > EveMonClient.OnCharacterListUpdated - 132378713013767165 (Uinen Star)
0d 0h 00m 11s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 11s > EveMonClient.OnESIKeyInfoUpdated - 132378713013767165 (Uinen Star)
0d 0h 00m 11s > EveMonClient.OnCharacterUpdated - Dodixie Flatline
0d 0h 00m 11s > EveMonClient.OnCharacterListUpdated - 132378712367384683 (Dodixie Flatline)
0d 0h 00m 11s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 11s > EveMonClient.OnESIKeyInfoUpdated - 132378712367384683 (Dodixie Flatline)
0d 0h 00m 11s > EveMonClient.OnCharacterUpdated - Anthony VonBrewskies
0d 0h 00m 11s > EveMonClient.OnCharacterListUpdated - 132378712024251842 (Anthony VonBrewskies)
0d 0h 00m 11s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 11s > EveMonClient.OnESIKeyInfoUpdated - 132378712024251842 (Anthony VonBrewskies)

0d 0h 00m 11s > ExceptionHandler.LogException - Handled exception
    System.IO.IOException: The process cannot access the file 'C:\Users\JB\AppData\Local\Temp\tmpD7D5.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at EVEMon.Common.Helpers.FileHelper.<OverwriteOrWarnTheUserAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Settings.<SaveImmediateAsync>d__86.MoveNext()
    
0d 0h 00m 11s > UpdateManager.OnCheckCompleted
0d 0h 00m 11s > UpdateManager.ScheduleCheck - in 12:00:00
0d 0h 00m 12s > EveMonClient.OnCharacterWalletTransactionsUpdated - Anika Dark
0d 0h 00m 13s > EveMonClient.OnCharacterSkillQueueUpdated - Zhilia Mann
0d 0h 00m 13s > EveMonClient.OnCharacterSkillQueueUpdated - Uinen Star
0d 0h 00m 13s > EveMonClient.OnCharacterSkillQueueUpdated - Anika Dark
0d 0h 00m 13s > EveMonClient.OnCharacterSkillQueueUpdated - Dodixie Flatline
0d 0h 00m 13s > EveMonClient.OnCharacterSkillQueueUpdated - Ra'ita
0d 0h 00m 13s > EveMonClient.OnCharacterSkillQueueUpdated - Doma I Magnetoque
0d 0h 00m 13s > EveMonClient.OnCharacterSkillQueueUpdated - Anthony VonBrewskies
0d 0h 00m 14s > EveMonClient.OnCharacterImplantSetCollectionChanged - Anika Dark
0d 0h 00m 14s > EveMonClient.OnCharacterImplantSetCollectionChanged - Ra'ita
0d 0h 00m 14s > EveMonClient.OnCharacterImplantSetCollectionChanged - Uinen Star
0d 0h 00m 14s > EveMonClient.OnCharacterImplantSetCollectionChanged - Zhilia Mann
0d 0h 00m 14s > EveMonClient.OnCharacterImplantSetCollectionChanged - Doma I Magnetoque
0d 0h 00m 15s > EveMonClient.OnCharacterImplantSetCollectionChanged - Dodixie Flatline
0d 0h 00m 15s > EveMonClient.OnCharacterImplantSetCollectionChanged - Anthony VonBrewskies
0d 0h 00m 15s > EveMonClient.OnCharacterUpdated - Anika Dark
0d 0h 00m 15s > EveMonClient.OnCharacterInfoUpdated - Anika Dark
0d 0h 00m 15s > EveMonClient.OnCharacterImplantSetCollectionChanged - Anika Dark
0d 0h 00m 15s > EveMonClient.OnCharacterUpdated - Ra'ita
0d 0h 00m 15s > EveMonClient.OnCharacterInfoUpdated - Ra'ita
0d 0h 00m 15s > EveMonClient.OnCharacterImplantSetCollectionChanged - Ra'ita
0d 0h 00m 15s > EveMonClient.OnCharacterUpdated - Zhilia Mann
0d 0h 00m 15s > EveMonClient.OnCharacterInfoUpdated - Zhilia Mann
0d 0h 00m 15s > EveMonClient.OnCharacterImplantSetCollectionChanged - Zhilia Mann
0d 0h 00m 15s > EveMonClient.OnCharacterUpdated - Doma I Magnetoque
0d 0h 00m 15s > EveMonClient.OnCharacterInfoUpdated - Doma I Magnetoque
0d 0h 00m 15s > EveMonClient.OnCharacterImplantSetCollectionChanged - Doma I Magnetoque
0d 0h 00m 15s > EveMonClient.OnCharacterUpdated - Uinen Star
0d 0h 00m 15s > EveMonClient.OnCharacterInfoUpdated - Uinen Star
0d 0h 00m 15s > EveMonClient.OnCharacterImplantSetCollectionChanged - Uinen Star
0d 0h 00m 15s > EveMonClient.OnCharacterUpdated - Anthony VonBrewskies
0d 0h 00m 15s > EveMonClient.OnCharacterInfoUpdated - Anthony VonBrewskies
0d 0h 00m 15s > EveMonClient.OnCharacterImplantSetCollectionChanged - Anthony VonBrewskies
0d 0h 00m 16s > EveMonClient.OnCharacterUpdated - Dodixie Flatline
0d 0h 00m 16s > EveMonClient.OnCharacterInfoUpdated - Dodixie Flatline
0d 0h 00m 16s > EveMonClient.OnCharacterImplantSetCollectionChanged - Dodixie Flatline
0d 0h 00m 17s > EveMonClient.OnEveIDToNameUpdated
0d 0h 00m 18s > Program.StartupAsync
0d 0h 00m 18s > Closed
```

**Comment by peterhaneve** [comment]
`System.IO.IOException: The process cannot access the file '...' because it is being used by another process`
This is an entirely different crash. It is likely due to conflicts with an anti-virus or other program, or a timing issue (if EVEMon was just updated through the installer).
