### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by sarthak40** [peterhaneve/evemon#264]
I am getting the following trace when attempting to add a character on the account. (Followed https://peterhaneve.github.io/evemon-esi)

Any suggestions?

```
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Program.StartupAsync - done
0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 00s > Settings.TryDeserializeFromFile - done
0d 0h 00m 00s > Settings.Import - begin
0d 0h 00m 00s > EveMonClient.OnSchedulerChanged
0d 0h 00m 00s > Settings.Import - done
0d 0h 00m 00s > EveMonClient.OnSettingsChanged
0d 0h 00m 00s > Main loop - start
0d 0h 00m 01s > MainWindow.OnLoad
0d 0h 00m 01s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 01s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 01s > Main window - loaded
0d 0h 00m 01s > Datafiles.Load - begin
0d 0h 00m 02s > TimeCheck.BeginCheckAsync
0d 0h 00m 02s > TimeCheck.OnCheckCompleted - Synchronised
0d 0h 00m 02s > TimeCheck.ScheduleCheck - in 1.00:00:00
0d 0h 00m 02s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 06s > Datafiles.Load - done
0d 0h 00m 06s > Settings.ImportData - begin
0d 0h 00m 06s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 06s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 06s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 07s > Settings.ImportData - done
0d 0h 00m 07s > EveMonClient.OnSettingsChanged
0d 0h 00m 12s > UpdateManager.OnCheckCompleted
0d 0h 00m 12s > UpdateManager.ScheduleCheck - in 12:00:00

0d 0h 00m 42s > ExceptionHandler.LogException - Handled exception
    EVEMon.Common.Net.HttpWebClientServiceException: A request to login.eveonline.com failed with status: SecureChannelFailure. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Net.HttpWebClientService.<DownloadStringAsync>d__2.MoveNext()
```

**Comment by peterhaneve** [comment]
It looks like there is a mismatch between the enabled SSL modes (try changing them in Internet Options) on your computer and the modes supported by ESI. Alternatively, parental control or firewall software might be transparently installing a MITM certificate that could cause this issue.
