### ISSUE TITLE
Error Message with EVemon

### ISSUE THREAD

**Issue by GerrytheViking** [peterhaneve/evemon#312]
EVEMon 4.0.20.4986

API Error:
Error querying the character sheet for Selakk.
HTTP error: A request to esi.evetech.net failed with status: 404 (Not Found).

**Comment by GerrytheViking** [comment]
EVEMon.Common.Net.HttpWebClientServiceException: A request to esi.evetech.net failed with status: 404 (Not Found). ---> System.Net.Http.HttpRequestException: Der Antwortstatuscode gibt keinen Erfolg an: 404 (Not Found).
   bei System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   bei EVEMon.Common.Net.HttpClientServiceRequest.EnsureSuccessStatusCode(HttpResponseMessage response)
   bei EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei EVEMon.Common.Net.HttpWebClientService.<DownloadStreamAsync>d__11`1.MoveNext()

**Comment by OverlordQ** [comment]
#300

**Comment by boneless3vil** [comment]
I'm having the same problem.

What I tried:
– deleting all my characters, ESI, resetting evemon and then uninstalling/reinstalling

Whether I'm starting out from a blank slate or not, it gives me the following error. Any solutions?

_EVEMon.Common.Net.HttpWebClientServiceException: A request to esi.evetech.net failed with status: 404 (Not Found). ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at EVEMon.Common.Net.HttpClientServiceRequest.EnsureSuccessStatusCode(HttpResponseMessage response)
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Net.HttpWebClientService.<DownloadStreamAsync>d__11`1.MoveNext()_

**Comment by doomlord289** [comment]
@GerrytheViking and @boneless3vil you might want to check out https://github.com/mgoeppner/evemon. It seems to be the actively maintained fork of evemon at the moment. The dev's first change was fixing this error that occurred because CCP removed an API endpoint.
