### ISSUE TITLE
Error QUerying Character Sheet

### ISSUE THREAD

**Issue by zaxlofful** [peterhaneve/evemon#317]
EVEMon 4.0.20.4986

API Error:
Error querying the character sheet for [Name}.
HTTP error: A request to esi.evetech.net failed with status: 404 (Not Found).

EVEMon.Common.Net.HttpWebClientServiceException: A request to esi.evetech.net failed with status: 404 (Not Found). ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at EVEMon.Common.Net.HttpClientServiceRequest.EnsureSuccessStatusCode(HttpResponseMessage response)
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Net.HttpWebClientService.<DownloadStreamAsync>d__11`1.MoveNext()

**Comment by doomlord289** [comment]
@ZaxLofful you might want to check out https://github.com/mgoeppner/evemon. It seems to be the actively maintained fork of evemon at the moment. The dev's first change was fixing this error that occurred because CCP removed an API endpoint.

**Comment by zaxlofful** [comment]
Yeah, I realized that after I posted this.
