### ISSUE TITLE
Rare error in Skill Explorer & suspicious code

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#67]
**Note Fixed in Pull Request commit: 7ead0e9.**

I right clicked a skill in the Skill Explorer and got the trace below. Basically is what happens is that in a check to throw a harmless exception you have a full exception.

Easy to reproduce, open a skill in the Skill browser, Click one and show it in the Skill Explorer, right click the topmost skill (so the skill opened) and select Show in Skill Browser.

I think the line 437 points to flawed code:
`skill.ThrowIfNull(nameof(skill));`

ThrowIfNull() on its turn uses:
`if (obj.Equals(null)) { }`

which is flawed as when the skill and obj are null, Equals cannot be called.

The line should read:
`if (obj==null) { }`

Although to my surprise extension method work on null values of an object, I personally would prefer 
a bit more work and replace all extension calls by a static method like (as it also moves the nameof() call to a single spot):

```
      public static void ThrowIfNull<T>(T obj, string message = null)
        {
            if (obj == null)
            {
                throw new ArgumentNullException(nameof(obj), message ?? "Value cannot be null.");
            }
        }
```

in the Util.cs class and use calls like:
`Util.ThrowIfNull(skill);`

```
EVEMon Version: 4.0.7.4839
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.17134.0
Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe" 
System.NullReferenceException: Object reference not set to an instance of an object.
   at EVEMon.Common.Extensions.ObjectExtensions.ThrowIfNull[T](T obj, String paramName, String message) in EVEMon.Common\Extensions\ObjectExtensions.cs:line 17
   at EVEMon.SkillPlanner.PlanWindow.ShowSkillInBrowser(Skill skill) in EVEMon\SkillPlanner\PlanWindow.cs:line 437
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Datafile report:
  eve-blueprints-en-US.xml.gzip (201KiB - 219eb76e35e9c1df32d2b7f21268582c)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (1009KiB - 9a7a4fc5ca3340dc0c91f3116810d107)
  eve-items-en-US.xml.gzip (2403KiB - 00ce5d7ad1efce9283e08b2c4249ecbe)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (61KiB - 1f047494a5dbcd31d9675257dc49098a)
  eve-reprocessing-en-US.xml.gzip (110KiB - e66052e6ad68555d0e14479a2b352280)
  eve-skills-en-US.xml.gzip (24KiB - 8684157679e5345a8b91d5ce15e0dd4f)

0d 0h 01m 00s > ExceptionHandler.LogException - Handled exception
    System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: <eveapi xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read553_NotificationRefTypes()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at EVEMon.Common.Util.DeserializeXmlFromFile[T](String filename, XslCompiledTransform transform) in EVEMon.Common\Util.cs:line 101
    
0d 0h 01m 00s > LocalXmlCache.Load - Failed to load data from file NotificationRefTypes; deleting file
0d 0h 01m 01s > EveMonClient.OnNotificationInvalidated
0d 0h 01m 02s > EveMonClient.OnNotificationRefTypesUpdated
0d 0h 01m 06s > EveMonClient.OnEveIDToNameUpdated

```

**Comment by wvdvegt** [comment]
Bug might be a bit more complex (at least the `SkillBrowser `part).
In the debugger the thrown exception does not trigger a popup, outside VS it does.

So a fix in `ShowSkillInBrowser `is either to make sure the `miShowInSkillBrowser`_Click and `miShowInSkillExplorer`_Click do not do a popup when the skill is null (return when skill is null) or better make sure the `Tag ` property in 
`Skill skill = ((PlanEntry)lvSkills.SelectedItems[0]?.Tag)?.CharacterSkill;`
has a value.

I appended a new commit with two return statements (won't harm).
