### ISSUE TITLE
Evemon attempting to query NPC corporation contracts

### ISSUE THREAD

**Issue by krynnotaur** [peterhaneve/evemon#81]
Character that was in player corp now in NPC corp; evemon is attempting to query contracts from an NPC corp that cannot be queried. I wager there were contracts in progress from the player corp and this corner case is not handled correctly.

EVEMon.Common.Net.HttpWebClientServiceException: A request to esi.evetech.net failed with status: 403 (Forbidden). ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at EVEMon.Common.Net.HttpClientServiceRequest.EnsureSuccessStatusCode(HttpResponseMessage response) in U:\Users\Stephen\Documents\PRGM\EVEMon\src\EVEMon.Common\Net\HttpClientServiceRequest.cs:line 123
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext() in U:\Users\Stephen\Documents\PRGM\EVEMon\src\EVEMon.Common\Net\HttpClientServiceRequest.cs:line 65
   --- End of inner exception stack trace ---
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext() in U:\Users\Stephen\Documents\PRGM\EVEMon\src\EVEMon.Common\Net\HttpClientServiceRequest.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Net.HttpWebClientService.<DownloadStreamAsync>d__11`1.MoveNext() in U:\Users\Stephen\Documents\PRGM\EVEMon\src\EVEMon.Common\Net\HttpWebClientService.StreamDownload.cs:line 36

**Comment by peterhaneve** [comment]
EVEMon normally suppresses this error, but CCP recently changed the 403 message, which used to include a remark about the character lacking roles. Since this is no longer easy to distinguish, I went through and blocked all corporation data querying if the character appears to be in an NPC corp.
