### ISSUE TITLE
Crash in Wine when adding Characters

### ISSUE THREAD

**Issue by steven-tk** [peterhaneve/evemon#97]
Hey there! :)

Crashes after clicking File->Add Character if you run it via Wine (.NET4.6.2 in latest Crossover on MacOS 10.14).
Adding the ESI info in settings worked fine.
According to https://forums.eveonline.com/t/evemon-4-0-8-esi-edition/75953/229 there is a workaround if you have access to a windows machine (which I don't).

If it can't be fixed for now is there a way to manually edit the settings file as another workaround e.g. in atom?

--

EVEMon Version: 4.0.8.4849
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
Executable Path: "C:\Program Files\EVEMon\EVEMon.exe"
System.Net.HttpListenerException (0x80004005): Access denied
   at System.Net.HttpListener.SetupV2Config()
   at System.Net.HttpListener.ValidateV2Property()
   at EVEMon.Common.Service.SSOWebServer..ctor()
   at EVEMon.ApiCredentialsManagement.EsiKeyUpdateOrAdditionWindow..ctor()
   at EVEMon.MainWindow.addAPIKeyMenu_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Datafile report:
  eve-blueprints-en-US.xml.gzip (201KiB - 219eb76e35e9c1df32d2b7f21268582c)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (1010KiB - 062c656d9913c91533ec4bca655b4825)
  eve-items-en-US.xml.gzip (2433KiB - ac5cb0e021653cc4f9e3b27528741b2c)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (61KiB - d74b9e0d0a28ac14fea54abb29fca45c)
  eve-reprocessing-en-US.xml.gzip (110KiB - f1bf6c569f131eb478e080ebe3a68762)
  eve-skills-en-US.xml.gzip (24KiB - 8684157679e5345a8b91d5ce15e0dd4f)

Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 01s > EveMonClient.Initialize - done
0d 0h 00m 01s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 02s > Settings.TryDeserializeFromFile - done
0d 0h 00m 02s > Settings.Import - begin
0d 0h 00m 03s > EveMonClient.OnSchedulerChanged
0d 0h 00m 03s > Settings.Import - done
0d 0h 00m 03s > EveMonClient.OnSettingsChanged
0d 0h 00m 03s > Main loop - start
0d 0h 00m 04s > MainWindow.OnLoad
0d 0h 00m 04s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 10s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 10s > Main window - loaded
0d 0h 00m 10s > Datafiles.Load - begin
0d 0h 00m 10s > TimeCheck.BeginCheckAsync
0d 0h 00m 19s > TimeCheck.OnCheckCompleted - Synchronised
0d 0h 00m 20s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 23s > UpdateManager.OnCheckCompleted
0d 0h 00m 23s > UpdateManager.ScheduleCheck - in 12:00:00
0d 0h 00m 26s > TimeCheck.ScheduleCheck - in 1.00:00:00
0d 0h 00m 30s > Datafiles.Load - done
0d 0h 00m 30s > Settings.ImportData - begin
0d 0h 00m 30s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 30s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 30s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 31s > Settings.ImportData - done
0d 0h 00m 31s > EveMonClient.OnSettingsChanged
0d 0h 02m 47s > Settings.Import - begin
0d 0h 02m 47s > EveMonClient.OnSchedulerChanged
0d 0h 02m 47s > Settings.Import - done
0d 0h 02m 47s > EveMonClient.OnSettingsChanged
0d 0h 03m 21s > Settings.Import - begin
0d 0h 03m 21s > EveMonClient.OnSchedulerChanged
0d 0h 03m 21s > Settings.Import - done
0d 0h 03m 21s > EveMonClient.OnSettingsChanged
0d 0h 03m 23s > Settings.Import - begin
0d 0h 03m 23s > EveMonClient.OnSchedulerChanged
0d 0h 03m 23s > Settings.Import - done
0d 0h 03m 23s > EveMonClient.OnSettingsChanged

**Comment by peterhaneve** [comment]
This issue is likely due to the HttpListener class in Wine behaving differently than in Windows. In the Windows version, no firewall exception is necessary for listening on localhost only, which eliminates a need to add one in the installer.

I do not have a Wine machine to test, but adding the exception manually as shown in https://stackoverflow.com/a/4115328 may solve the issue. There is no good way to solve this on the EVEMon side without breaking Windows compatibility, even after PKCE is added.
